permalink: /:categories/:title.html
url: "http://isbhargav.github.io/showcase/"
full_name: "Bhargav Lad"
first_name: "Bhargav"
last_name: "lad"
blog_title: "Showcase "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: ""
copyright_year: "2021"
google_analytics_code: ""
aboutme: "Graduate student"
twitter: "bhargavlad"
github: "isbhargav"
facebook: ""
linkined_url: ""
